// vue-app/src/App.vue
<script>
let id = 0;

export default {
  name: "App",
  data() {
    return {
      newTodo: "",
      todos: [],
      totalTime: "0",
      totalItems: 0,
    };
  },
  methods: {
    addXItems(num) {
      let t0 = performance.now();
      for (let i = 0; i < num; i++) {
        this.todos.push({ id: id++, text: this.newTodo, status: false });
      }
      this.newTodo = "";
      let t1 = performance.now();
      let time = t1 - t0;
      this.totalTime =
        time < 1000 ? time.toFixed(3) + " ms" : time / 1000 + " s";
      this.totalItems = this.todos.length;
    },
    removeTodo(todo) {
      this.todos = this.todos.filter((t) => t !== todo);
    },
  },
};
</script>

<template>
  <div id="container">
    <div class="header">
      <h1>Vue Todo List</h1>
      <img
        class="logo"
        src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/2367px-Vue.js_Logo_2.svg.png"
        alt="logo"
      />
      <div class="results-container">
        <p>
          Total Time: <span class="results">{{ totalTime }}</span>
        </p>
        <p>
          Total Items: <span class="results">{{ totalItems }}</span>
        </p>
      </div>
    </div>
    <form id="add" @submit.prevent="addTodo">
      <div class="input-container">
        <input id="input-text" v-model="newTodo" />
      </div>
      <div class="todo-buttons">
        <button class="add-todo-button" @click="addXItems(1)">Add 1</button>
        <button class="add-todo-button" @click="addXItems(1000)">Add 1K</button>
        <button class="add-todo-button" @click="addXItems(5000)">Add 5K</button>
        <button class="add-todo-button" @click="addXItems(10000)">
          Add 10K
        </button>
        <button class="add-todo-button" @click="addXItems(50000)">
          Add 50K
        </button>
        <button class="add-todo-button" @click="addXItems(100000)">
          Add 100K
        </button>
      </div>
    </form>
    <ul class="todos">
      <li class="todo" v-for="todo in todos" :key="todo.id">
        <input type="checkbox" v-model="todo.status" />
        <span class="text" :class="{ checked: todo.status }">{{
          todo.text
        }}</span>
        <button class="button" @click="removeTodo(todo)">x</button>
      </li>
    </ul>
  </div>
</template>

<style>
@import "./styles.css";
</style>

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'todo';
  totalTime = '0';
  totalItems = 0;

  allItems: { description: string; status: boolean }[] = [];

  addXItems(items: number, description: string) {
    let t0 = performance.now();
    for (let i = 0; i < items; i++) {
      this.allItems.unshift({ description, status: false });
    }
    let t1 = performance.now();
    let time = t1 - t0;
    this.totalTime = time < 1000 ? time.toFixed(3) + ' ms' : time / 1000 + ' s';
    this.totalItems = this.todos.length;
  }

  completeItem(todo: any) {
    todo.status = !todo.status;
  }

  removeTodos(todo: any) {
    this.allItems = this.allItems.filter((t) => t !== todo);
  }

  get todos() {
    return this.allItems;
  }
}

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
      Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji",
      "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
</style>

<div id="container">
  <div class="header">
    <h1>My To Do List</h1>
    <img
      class="logo"
      src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/1200px-Angular_full_color_logo.svg.png"
      alt="logo"
    />
    <div class="results-container">
      <p>
        Total time: <span class="results" id="total-time">{{ totalTime }}</span>
      </p>
      <p>
        Total items:
        <span class="results" id="total-items">{{ totalItems }}</span>
      </p>
    </div>
  </div>

  <div id="add">
    <div class="input-container">
      <input
        #newItem
        placeholder="add an item"
        (keyup.enter)="addXItems(1, newItem.value); newItem.value = ''"
        class="lg-text-input"
        id="input-text"
      />
    </div>

    <button class="add-todo-button" (click)="addXItems(1, newItem.value)">
      Add 1
    </button>
    <button class="add-todo-button" (click)="addXItems(1000, newItem.value)">
      Add 1K
    </button>
    <button class="add-todo-button" (click)="addXItems(5000, newItem.value)">
      Add 5K
    </button>
    <button class="add-todo-button" (click)="addXItems(10000, newItem.value)">
      Add 10K
    </button>
    <button class="add-todo-button" (click)="addXItems(50000, newItem.value)">
      Add 50K
    </button>
    <button class="add-todo-button" (click)="addXItems(100000, newItem.value)">
      Add 100K
    </button>
  </div>

  <ul class="todos">
    <li class="todo" *ngFor="let todo of todos">
      <input type="checkbox" (click)="completeItem(todo)" />
      <span class="text" [ngClass]="{ checked: todo.status }">
        {{ todo.description }}
      </span>
      <button (click)="removeTodos(todo)">x</button>
    </li>
  </ul>
</div>
