// react-app/src/App.jsx
import { useState } from "react";

function App() {
  const [todos, setTodos] = useState([]);
  const [newTodo, setNewTodo] = useState("");
  const [totalTime, setTotalTime] = useState("0");
  const [totalItems, setTotalItems] = useState("0");

  const checkItem = (cur) => {
    const newTodos = todos.map((t) => {
      if (t === cur) {
        t.status = !t.status;
      }
      return t;
    });
    setTodos(newTodos);
  };

  const removeFromList = (td) => {
    const newTodos = todos.filter((t) => t !== td);
    setTodos(newTodos);
  };

  const addXItems = (num) => {
    const t0 = performance.now();
    const newItems = [];
    for (let i = 0; i < num; i++) {
      newItems.push({ text: newTodo, status: false });
    }
    setTodos([...todos, ...newItems]);
    const t1 = performance.now();
    const time = t1 - t0;
    // Getting DATA
    // const toWrite = `${num}: ${time} ms`;
    // console.log(toWrite);
    const totalTime =
      time < 1000 ? time.toFixed(3) + " ms" : (time / 1000).toFixed(2) + " s";
    setTotalTime(`${totalTime}`);
    setTotalItems(+totalItems + num);
  };

  return (
    <div id="container">
      <div className="header">
        <h1>React Todo List</h1>
        <img
          className="logo"
          src={
            "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1024px-React-icon.svg.png?20220125121207"
          }
          alt="javascript logo"
        />
        <div className="results-container">
          <p>
            Total Time: <span className="results">{totalTime}</span>
          </p>
          <p>
            Total Items: <span className="results">{totalItems}</span>
          </p>
        </div>
      </div>
      <div>
        <div className="input-container">
          <input
            type="text"
            id="input-text"
            placeholder="Add new todo..."
            value={newTodo}
            onChange={(e) => setNewTodo(e.target.value)}
          />
        </div>
        <div className="todo-buttons">
          <button className={"add-todo-button"} onClick={() => addXItems(1)}>
            Add 1
          </button>
          <button className={"add-todo-button"} onClick={() => addXItems(1000)}>
            Add 1K
          </button>
          <button className={"add-todo-button"} onClick={() => addXItems(5000)}>
            Add 5K
          </button>
          <button
            className={"add-todo-button"}
            onClick={() => addXItems(10000)}
          >
            Add 10K
          </button>
          <button
            className={"add-todo-button"}
            onClick={() => addXItems(50000)}
          >
            Add 50K
          </button>
          <button
            className={"add-todo-button"}
            onClick={() => addXItems(100000)}
          >
            Add 100K
          </button>
        </div>
      </div>
      <ul className={"todos"}>
        {todos.map((todo) => {
          return (
            <li className={"todo"}>
              <input type="checkbox" onClick={() => checkItem(todo)} />
              <span
                style={{
                  textDecoration: todo.status ? "line-through" : "none",
                }}
              >
                {todo.text}
              </span>
              <button onClick={() => removeFromList(todo)}>X</button>
            </li>
          );
        })}
      </ul>
    </div>
  );
}

export default App;

// vue-app/src/App.vue
<script>
let id = 0;

export default {
  name: "App",
  data() {
    return {
      newTodo: "",
      todos: [],
      totalTime: "0",
      totalItems: 0,
    };
  },
  methods: {
    addXItems(num) {
      let t0 = performance.now();
      for (let i = 0; i < num; i++) {
        this.todos.push({ id: id++, text: this.newTodo, status: false });
      }
      this.newTodo = "";
      let t1 = performance.now();
      let time = t1 - t0;
      this.totalTime =
        time < 1000 ? time.toFixed(3) + " ms" : time / 1000 + " s";
      this.totalItems = this.todos.length;
    },
    removeTodo(todo) {
      this.todos = this.todos.filter((t) => t !== todo);
    },
  },
};
</script>

<template>
  <div id="container">
    <div class="header">
      <h1>Vue Todo List</h1>
      <img
        class="logo"
        src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/2367px-Vue.js_Logo_2.svg.png"
        alt="logo"
      />
      <div class="results-container">
        <p>
          Total Time: <span class="results">{{ totalTime }}</span>
        </p>
        <p>
          Total Items: <span class="results">{{ totalItems }}</span>
        </p>
      </div>
    </div>
    <form id="add" @submit.prevent="addTodo">
      <div class="input-container">
        <input id="input-text" v-model="newTodo" />
      </div>
      <div class="todo-buttons">
        <button class="add-todo-button" @click="addXItems(1)">Add 1</button>
        <button class="add-todo-button" @click="addXItems(1000)">Add 1K</button>
        <button class="add-todo-button" @click="addXItems(5000)">Add 5K</button>
        <button class="add-todo-button" @click="addXItems(10000)">
          Add 10K
        </button>
        <button class="add-todo-button" @click="addXItems(50000)">
          Add 50K
        </button>
        <button class="add-todo-button" @click="addXItems(100000)">
          Add 100K
        </button>
      </div>
    </form>
    <ul class="todos">
      <li class="todo" v-for="todo in todos" :key="todo.id">
        <input type="checkbox" v-model="todo.status" />
        <span class="text" :class="{ checked: todo.status }">{{
          todo.text
        }}</span>
        <button class="button" @click="removeTodo(todo)">x</button>
      </li>
    </ul>
  </div>
</template>

<style>
@import "./styles.css";
</style>
